[package]
name = "cargo-about"
version = "0.3.0"
description = "Cargo plugin for generating a listing of all of the crates and the the terms under which they are licensed"
authors = [
  "Embark <opensource@embark-studios.com>",
  "Jake Shadle <jake.shadle@embark-studios.com>",
]
edition = "2018"
repository = "https://github.com/EmbarkStudios/cargo-about"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/cargo-about"
homepage = "https://github.com/EmbarkStudios/cargo-about"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "license", "spdx"]
exclude = ["media/"]

[badges]
maintenance = { status = "actively-developed" }

[[bin]]
name = "cargo-about"
path = "src/cargo-about/main.rs"

[dependencies]
# Colorization
ansi_term = "0.12"
# Error facilities
anyhow = "1.0"
# License detection
askalono = "0.4"
# TTY detection
atty = "0.2"
# Datetime
chrono = "0.4"
# Diagnostic reporting
codespan = "0.11"
codespan-reporting = "0.11"
# Logging helpers
fern = "0.6"
# Template engine for output
handlebars = { version = "4.1", features = ["dir_source"] }
# Directory walking
ignore = "0.4"
# Dependency graphing
krates = "0.8"
# Logging macros
log = "0.4"
# Better locking primitives
parking_lot = "0.11"
# brrrr
rayon = "1.5"
# HTTP requests
reqwest = { version = "0.11", default-features = false, features = [
  "blocking",
  "rustls-tls",
] }
# Checksum verification (already pulled in via rustls)
ring = "0.16"
# Oh gee what could it be
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Some vecs don't need to hit the heap
smallvec = "1.7"
# License expression parsing and evaluation
spdx = { version = "0.6", features = ["text"] }
# Command line parsing
structopt = "0.3"
# Configuration parsing
toml = "0.5"
# Manipulation of cargo manifests for diagnostic purposes
toml_edit = "0.6"
# Better heap allocator over system one (usually)
mimalloc = "0.1"

# API helpers for api.clearlydefined.io
[dependencies.cd]
path = "../clearly-defined"
features = ["blocking", "rustls"]

[patch.crates-io]
spdx = { path = "../spdx" }
krates = { path = "../krates" }
