targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unsound = "deny"
unmaintained = "deny"
ignore = [
    # failure is unsound and unmaintained, but is used by askalono
    "RUSTSEC-2020-0036",
    "RUSTSEC-2019-0036",
    # chrono/time only used for datetime parsing
    "RUSTSEC-2020-0159",
    "RUSTSEC-2020-0071",
]

[bans]
multiple-versions = "deny"
deny = [
    # You can never be too sure
    { name = "openssl-sys" },
    # crates should use cc, not big separate build systems
    { name = "cmake" },
]
skip = [
    # clap uses old ansi-term
    { name = "ansi_term", version = "=0.11.0" },
    # old itertools from really old zstd from askalono, build only
    { name = "itertools", version = "=0.9.0" },
]

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "ISC"]

exceptions = [
    # ring uses code from multiple libraries but all with permissive licenses
    # https://tldrlegal.com/license/openssl-license-(openssl)
    { allow = ["ISC", "MIT", "OpenSSL"], name = "ring" },

    # MPL 2.0 is a copyleft license and we HAVE to disclose
    # the source code of these specific libraries if we do changes to it.
    # which we do through public forks of the repos if/when we do changes to it.
    # https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)
    { allow = ["MPL-2.0"], name = "webpki-roots" },
]

[[licenses.clarify]]
name = "ring"
# SPDX considers OpenSSL to encompass both the OpenSSL and SSLeay licenses
# https://spdx.org/licenses/OpenSSL.html
# ISC - Both BoringSSL and ring use this for their new files
# MIT - "Files in third_party/ have their own licenses, as described therein. The MIT
# license, for third_party/fiat, which, unlike other third_party directories, is
# compiled into non-test libraries, is included below."
# OpenSSL - Obviously
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]
