[bans]
multiple-versions = "deny"
deny = [
    # You can never be too sure
    { name = "openssl-sys" },
]
skip = [
    # ignore uses an old crossbeam-channel
    { name = "crossbeam-utils", version = "=0.6.6" },
    # crossbeam uses an old autocfg
    { name = "autocfg", version = "0.1.7" },
    # ignore uses an old thread_local
    { name = "thread_local", version = "0.3.6" },
]

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
]
