[bans]
multiple-versions = "deny"
deny = [
    # You can never be too sure
    { name = "openssl" },
]
skip = [
    # ignore uses an old crossbeam-channel
    { name = "crossbeam-utils", version = "=0.6.6" },
]

[licenses]
unlicensed = "deny"
unknown = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
]
