on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

name: CI
jobs:
  arm_test:
    name: Build aarch64-apple-darwin
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup target add aarch64-apple-darwin
      - run: cargo fetch --target aarch64-apple-darwin
      - run: cargo build --release --target aarch64-apple-darwin
      - run: cargo run --release --target aarch64-apple-darwin -- --version
